<a href="https://colab.research.google.com/github/sgulyano/imgvdoproc/blob/main/lab_dft.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lab: DFT and IDFT

For 18-793 Image and Video Processing course. By Sarun Gulyanon.

This lab introduces the Discrete Fourier Transform (DFT) and Inverse Discrete Fourier Transform (IDFT) through a direct, brute-force (intentionally inefficient) implementation to emphasize the underlying mathematical concepts.

# DFT

In [2]:
import cmath
import math

In [3]:
def dft(f):
    """
    Compute DFT using:
        F(u) = sum_{x=0}^{M-1} f(x) * exp(-j * 2*pi*u*x / M)
    """
    M = len(f)
    F = []
    for u in range(M):
        s = 0j
        for x in range(M):
            s += f[x] * cmath.exp(-1j * 2 * math.pi * u * x / M)
        F.append(s)
    return F

In [4]:
# Example from your image: f(x) = [1, 2, 4, 4], M = 4
f = [1, 2, 4, 4]
F = dft(f)

for u, val in enumerate(F):
    print(f"F({u}) = {val}")

F(0) = (11+0j)
F(1) = (-3.000000000000001+1.9999999999999996j)
F(2) = (-1-7.347880794884119e-16j)
F(3) = (-2.9999999999999982-2.0000000000000018j)


# IDFT

In [5]:
def idft(F):
    """
    Compute IDFT using:
        f(x) = (1/M) * sum_{u=0}^{M-1} F(u) * exp(j*2*pi*u*x/M)
    """
    M = len(F)
    f = []
    for x in range(M):
        s = 0j
        for u in range(M):
            s += F[u] * cmath.exp(1j * 2 * math.pi * u * x / M)
        f.append(s / M)
    return f

In [6]:
f = idft(F)

for x, val in enumerate(f):
    print(f"f({x}) = {val.real:.6f}")

f(0) = 1.000000
f(1) = 2.000000
f(2) = 4.000000
f(3) = 4.000000


# 2D Image

In [12]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [9]:
def dft2(img):
    """
    2D DFT (brute force) using the definition:
        F(u,v) = sum_{x=0}^{M-1} sum_{y=0}^{N-1} f(x,y) * exp(-j*2*pi*(u*x/M + v*y/N))
    """
    img = np.asarray(img, dtype=np.complex128)
    M, N = img.shape
    F = np.zeros((M, N), dtype=np.complex128)

    for u in range(M):
        for v in range(N):
            s = 0j
            for x in range(M):
                for y in range(N):
                    s += img[x, y] * np.exp(-1j * 2 * np.pi * ((u * x) / M + (v * y) / N))
            F[u, v] = s
    return F


def idft2(F):
    """
    2D IDFT (brute force) using the definition:
        f(x,y) = (1/(M*N)) * sum_{u=0}^{M-1} sum_{v=0}^{N-1} F(u,v) * exp(+j*2*pi*(u*x/M + v*y/N))
    """
    F = np.asarray(F, dtype=np.complex128)
    M, N = F.shape
    img = np.zeros((M, N), dtype=np.complex128)

    for x in range(M):
        for y in range(N):
            s = 0j
            for u in range(M):
                for v in range(N):
                    s += F[u, v] * np.exp(1j * 2 * np.pi * ((u * x) / M + (v * y) / N))
            img[x, y] = s / (M * N)
    return img

In [13]:
# Small example image (4x4) for demonstration
img = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9,10,11,12],
    [13,14,15,16]
], dtype=float)

F = dft2(img)
print(F)

recon = idft2(F)

# recon should match img (up to tiny numerical error)
print("Original:\n", img)
print("\nReconstructed (real part):\n", np.real(recon))
print("\nMax abs error:", np.max(np.abs(np.real(recon) - img)))


[[136. +0.j  -8. +8.j  -8. -0.j  -8. -8.j]
 [-32.+32.j   0. +0.j   0. +0.j  -0. +0.j]
 [-32. -0.j   0. +0.j   0. +0.j  -0. +0.j]
 [-32.-32.j  -0. +0.j  -0. +0.j  -0. +0.j]]
Original:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Reconstructed (real part):
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

Max abs error: 1.3433698597964394e-14


----